allow_experimental_apis = true
sources = files(
        'main.c',
)

cflags += ['-I/home/lgf/dasics/dmachecker/dpdk-rootfs/libs/LibDASICS/repo/include']
ldflags += ['-L/home/lgf/dasics/dmachecker/dpdk-rootfs/libs/LibDASICS/build']
ldflags += ['-lDASICS']
ldflags += ['-T/home/lgf/dasics/dmachecker/dpdk-rootfs/libs/LibDASICS/repo/ld.lds']